version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432" # Expose PostgreSQL on port 5433 to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./personal-finance-api/sql/:/docker-entrypoint-initdb.d/
    networks:
      - finance-network

  api:
    build: ./personal-finance-api
    container_name: finance-api
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      OAUTH2_AUDIENCE: ${OAUTH2_AUDIENCE}
      OAUTH2_ISSUER_URI: ${OAUTH2_ISSUER_URI}
    ports:
      - "8080:8080"
    networks:
      - finance-network

  ui:
    build: ./personal-finance-ui
    container_name: finance-ui
    depends_on:
      - api
    ports:
      - "3000:80" # Expose frontend on port 3000 of host machine
    networks:
      - finance-network

volumes:
  postgres_data:

networks:
  finance-network:
    driver: bridge